[package]
distribution = "2201.9.0-20240314-004000-04275c0e""
org = "ballerinax"
name = "docusign.dsesign"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["eSignature", "Cost/Freemium", "Documents", "Collaboration", "Digital Signature"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-docusign.dsesign"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
