[package]
distribution = "2201.8.5"
org = "ballerinax"
name = "docusign.dsesign"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["eSignature", "Cost/Freemium", "Documents", "Collaboration", "Digital Signature"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-docusign"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
