[package]
distribution = "2201.8.0"
org = "ballerinax"
name = "docusign"
version = "0.1.0"
export=["docusign.admin", "docusign.click", "docusign.esign", "docusign.monitor", "docusign.rooms"]
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["digital signature"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-docusign"

[build-options]
observabilityIncluded = false

[platform.java17]
graalvmCompatible = true
